In [1]:
# ==========================================================
# AI-Assisted E-commerce Sales & Customer Analytics
# Data Cleaning - Part 1
# ==========================================================

# ==========================================================
# STEP 1 : Import Required Libraries
# ==========================================================

# Pandas is used for data manipulation and analysis
import pandas as pd

# NumPy is used for numerical operations
import numpy as np

# Display all columns while viewing DataFrames
pd.set_option('display.max_columns', None)

# Display wider output in Jupyter Notebook
pd.set_option('display.width', None)

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [2]:
# ==========================================================
# STEP 2 : Load All Datasets
# ==========================================================

customers = pd.read_csv("olist_customers_dataset.csv")

geolocation = pd.read_csv("olist_geolocation_dataset.csv")

order_items = pd.read_csv("olist_order_items_dataset.csv")

order_payments = pd.read_csv("olist_order_payments_dataset.csv")

order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")

orders = pd.read_csv("olist_orders_dataset.csv")

products = pd.read_csv("olist_products_dataset.csv")

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [3]:
# ==========================================================
# STEP 3 : Display First Five Records
# Purpose:
# View sample records from each dataset.
# ==========================================================

print("Customers Dataset")
display(customers.head())

print("Geolocation Dataset")
display(geolocation.head())

print("Order Items Dataset")
display(order_items.head())

print("Order Payments Dataset")
display(order_payments.head())

print("Order Reviews Dataset")
display(order_reviews.head())

print("Orders Dataset")
display(orders.head())

print("Products Dataset")
display(products.head())

Customers Dataset

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

Geolocation Dataset

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

Order Items Dataset

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

Order Payments Dataset

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

Order Reviews Dataset

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

Orders Dataset

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

Products Dataset

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [4]:
# ==========================================================
# STEP 4 : Check Dataset Dimensions
# Purpose:
# Display number of rows and columns.
# ==========================================================

print("Customers :", customers.shape)

print("Geolocation :", geolocation.shape)

print("Order Items :", order_items.shape)

print("Order Payments :", order_payments.shape)

print("Order Reviews :", order_reviews.shape)

print("Orders :", orders.shape)

print("Products :", products.shape)

Customers : (99441, 5)
Geolocation : (1000163, 5)
Order Items : (112650, 7)
Order Payments : (103886, 5)
Order Reviews : (100000, 7)
Orders : (99441, 8)
Products : (32951, 9)

In [5]:
# ==========================================================
# STEP 5 : Display Dataset Information
# Purpose:
# Check column names, data types and missing values.
# ==========================================================

print("\nCustomers Dataset Information")
customers.info()

print("\nGeolocation Dataset Information")
geolocation.info()

print("\nOrder Items Dataset Information")
order_items.info()

print("\nOrder Payments Dataset Information")
order_payments.info()

print("\nOrder Reviews Dataset Information")
order_reviews.info()

print("\nOrders Dataset Information")
orders.info()

print("\nProducts Dataset Information")
products.info()

Customers Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

Geolocation Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

Order Items Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

Order Payments Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

Order Reviews Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   review_id                100000 non-null  str
 1   order_id                 100000 non-null  str
 2   review_score             100000 non-null  int64
 3   review_comment_title     11715 non-null   str
 4   review_comment_message   41753 non-null   str
 5   review_creation_date     100000 non-null  str
 6   review_answer_timestamp  100000 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

Orders Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

Products Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [6]:
# ==========================================================
# STEP 6 : Display Statistical Summary
# Purpose:
# Generate summary statistics for numerical columns.
# ==========================================================

print("\nCustomers")
display(customers.describe(include='all'))

print("\nGeolocation")
display(geolocation.describe(include='all'))

print("\nOrder Items")
display(order_items.describe(include='all'))

print("\nOrder Payments")
display(order_payments.describe(include='all'))

print("\nOrder Reviews")
display(order_reviews.describe(include='all'))

print("\nOrders")
display(orders.describe(include='all'))

print("\nProducts")
display(products.describe(include='all'))

Customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441.000000,99441,99441
unique,99441,96096,NaN,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,NaN,sao paulo,SP
freq,1,17,NaN,15540,41746
mean,NaN,NaN,35137.474583,NaN,NaN
std,NaN,NaN,29797.938996,NaN,NaN
min,NaN,NaN,1003.000000,NaN,NaN
25%,NaN,NaN,11347.000000,NaN,NaN
50%,NaN,NaN,24416.000000,NaN,NaN
75%,NaN,NaN,58900.000000,NaN,NaN
max,NaN,NaN,99990.000000,NaN,NaN

Geolocation

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
count,1.000163e+06,1.000163e+06,1.000163e+06,1000163,1000163
unique,NaN,NaN,NaN,8011,27
top,NaN,NaN,NaN,sao paulo,SP
freq,NaN,NaN,NaN,135800,404268
mean,3.657417e+04,-2.117615e+01,-4.639054e+01,NaN,NaN
std,3.054934e+04,5.715866e+00,4.269748e+00,NaN,NaN
min,1.001000e+03,-3.660537e+01,-1.014668e+02,NaN,NaN
25%,1.107500e+04,-2.360355e+01,-4.857317e+01,NaN,NaN
50%,2.653000e+04,-2.291938e+01,-4.663788e+01,NaN,NaN
75%,6.350400e+04,-1.997962e+01,-4.376771e+01,NaN,NaN
max,9.999000e+04,4.506593e+01,1.211054e+02,NaN,NaN

Order Items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
count,112650,112650.000000,112650,112650,112650,112650.000000,112650.000000
unique,98666,NaN,32951,3095,93318,NaN,NaN
top,8272b63d03f5f79c56e9e4120aec44ef,NaN,aca2eb7d00ea1a7b8ebd4e68314663af,6560211a19b47992c3666cc44a7e94c0,2018-03-01 02:50:48,NaN,NaN
freq,21,NaN,527,2033,21,NaN,NaN
mean,NaN,1.197834,NaN,NaN,NaN,120.653739,19.990320
std,NaN,0.705124,NaN,NaN,NaN,183.633928,15.806405
min,NaN,1.000000,NaN,NaN,NaN,0.850000,0.000000
25%,NaN,1.000000,NaN,NaN,NaN,39.900000,13.080000
50%,NaN,1.000000,NaN,NaN,NaN,74.990000,16.260000
75%,NaN,1.000000,NaN,NaN,NaN,134.900000,21.150000
max,NaN,21.000000,NaN,NaN,NaN,6735.000000,409.680000

Order Payments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,103886,103886.000000,103886,103886.000000,103886.000000
unique,99440,NaN,5,NaN,NaN
top,fa65dad1b0e818e3ccc5cb0e39231352,NaN,credit_card,NaN,NaN
freq,29,NaN,76795,NaN,NaN
mean,NaN,1.092679,NaN,2.853349,154.100380
std,NaN,0.706584,NaN,2.687051,217.494064
min,NaN,1.000000,NaN,0.000000,0.000000
25%,NaN,1.000000,NaN,1.000000,56.790000
50%,NaN,1.000000,NaN,1.000000,100.000000
75%,NaN,1.000000,NaN,4.000000,171.837500
max,NaN,29.000000,NaN,24.000000,13664.080000

Order Reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
count,100000,100000,100000.000000,11715,41753,100000,100000
unique,99173,99441,NaN,4600,36921,637,99010
top,c444278834184f72b1484dfe47de7f97,c88b1d1b157a9999ce368f218a407141,NaN,Recomendo,Muito bom,2017-12-19 00:00:00,2017-06-15 23:21:05
freq,3,3,NaN,426,230,466,4
mean,NaN,NaN,4.070890,NaN,NaN,NaN,NaN
std,NaN,NaN,1.359663,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,5.000000,NaN,NaN,NaN,NaN

Orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

Products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32951,32341,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
unique,32951,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,1e9e8ef04dbcff4541ed26657ea517e5,cama_mesa_banho,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,3029,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,NaN,NaN,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,NaN,NaN,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,NaN,NaN,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,NaN,NaN,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,NaN,NaN,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,NaN,NaN,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [7]:
# ==========================================================
# STEP 7 : Check Missing Values
# Purpose:
# Identify columns containing null values.
# ==========================================================

print("\nMissing Values - Customers")
print(customers.isnull().sum())

print("\nMissing Values - Geolocation")
print(geolocation.isnull().sum())

print("\nMissing Values - Order Items")
print(order_items.isnull().sum())

print("\nMissing Values - Order Payments")
print(order_payments.isnull().sum())

print("\nMissing Values - Order Reviews")
print(order_reviews.isnull().sum())

print("\nMissing Values - Orders")
print(orders.isnull().sum())

print("\nMissing Values - Products")
print(products.isnull().sum())

Missing Values - Customers
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Missing Values - Geolocation
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

Missing Values - Order Items
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Missing Values - Order Payments
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Missing Values - Order Reviews
review_id                      0
order_id                       0
review_score                   0
review_comment_title       88285
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Missing Values - Orders
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Missing Values - Products
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [8]:
# ==========================================================
# STEP 8 : Check Duplicate Records
# Purpose:
# Identify duplicate rows in each dataset.
# ==========================================================

print("Duplicate Records")

print("Customers :", customers.duplicated().sum())

print("Geolocation :", geolocation.duplicated().sum())

print("Order Items :", order_items.duplicated().sum())

print("Order Payments :", order_payments.duplicated().sum())

print("Order Reviews :", order_reviews.duplicated().sum())

print("Orders :", orders.duplicated().sum())

print("Products :", products.duplicated().sum())

Duplicate Records
Customers : 0
Geolocation : 261831
Order Items : 0
Order Payments : 0
Order Reviews : 0
Orders : 0
Products : 0

In [9]:
# ==========================================================
# STEP 9 : Remove Duplicate Records
# Purpose:
# Remove duplicate rows if present.
# ==========================================================

customers.drop_duplicates(inplace=True)

geolocation.drop_duplicates(inplace=True)

order_items.drop_duplicates(inplace=True)

order_payments.drop_duplicates(inplace=True)

order_reviews.drop_duplicates(inplace=True)

orders.drop_duplicates(inplace=True)

products.drop_duplicates(inplace=True)

print("Duplicate records removed successfully!")

Duplicate records removed successfully!

In [10]:
# ==========================================================
# STEP 10 : Verify Dataset Dimensions After Cleaning
# Purpose:
# Confirm updated dataset sizes.
# ==========================================================

print("Customers :", customers.shape)

print("Geolocation :", geolocation.shape)

print("Order Items :", order_items.shape)

print("Order Payments :", order_payments.shape)

print("Order Reviews :", order_reviews.shape)

print("Orders :", orders.shape)

print("Products :", products.shape)

Customers : (99441, 5)
Geolocation : (738332, 5)
Order Items : (112650, 7)
Order Payments : (103886, 5)
Order Reviews : (100000, 7)
Orders : (99441, 8)
Products : (32951, 9)

In [11]:
# ==========================================================
# STEP 11 : Check Data Types
# Purpose:
# Verify the data type of each column before cleaning.
# ==========================================================

print("Customers Data Types")
display(customers.dtypes)

print("Geolocation Data Types")
display(geolocation.dtypes)

print("Order Items Data Types")
display(order_items.dtypes)

print("Order Payments Data Types")
display(order_payments.dtypes)

print("Order Reviews Data Types")
display(order_reviews.dtypes)

print("Orders Data Types")
display(orders.dtypes)

print("Products Data Types")
display(products.dtypes)

Customers Data Types

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

Geolocation Data Types

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

Order Items Data Types

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

Order Payments Data Types

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

Order Reviews Data Types

review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

Orders Data Types

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

Products Data Types

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [12]:
# ==========================================================
# STEP 12 : Convert Date Columns
# Purpose:
# Convert object columns containing dates into datetime format.
# ==========================================================

orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"]
)

orders["order_approved_at"] = pd.to_datetime(
    orders["order_approved_at"]
)

orders["order_delivered_carrier_date"] = pd.to_datetime(
    orders["order_delivered_carrier_date"]
)

orders["order_delivered_customer_date"] = pd.to_datetime(
    orders["order_delivered_customer_date"]
)

orders["order_estimated_delivery_date"] = pd.to_datetime(
    orders["order_estimated_delivery_date"]
)

order_reviews["review_creation_date"] = pd.to_datetime(
    order_reviews["review_creation_date"]
)

order_reviews["review_answer_timestamp"] = pd.to_datetime(
    order_reviews["review_answer_timestamp"]
)

print("Date columns converted successfully!")

Date columns converted successfully!

In [13]:
# ==========================================================
# STEP 13 : Verify Date Conversion
# ==========================================================

orders.info()

order_reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   review_id                100000 non-null  str
 1   order_id                 100000 non-null  str
 2   review_score             100000 non-null  int64
 3   review_comment_title     11715 non-null   str
 4   review_comment_message   41753 non-null   str
 5   review_creation_date     100000 non-null  datetime64[us]
 6   review_answer_timestamp  100000 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(4)
memory usage: 5.3 MB

In [14]:
# ==========================================================
# STEP 14 : Remove Leading and Trailing Spaces
# Purpose:
# Clean text columns by removing unwanted spaces.
# ==========================================================

customers = customers.apply(
    lambda col: col.str.strip() if col.dtype == "object" else col
)

geolocation = geolocation.apply(
    lambda col: col.str.strip() if col.dtype == "object" else col
)

order_items = order_items.apply(
    lambda col: col.str.strip() if col.dtype == "object" else col
)

order_payments = order_payments.apply(
    lambda col: col.str.strip() if col.dtype == "object" else col
)

order_reviews = order_reviews.apply(
    lambda col: col.str.strip() if col.dtype == "object" else col
)

orders = orders.apply(
    lambda col: col.str.strip() if col.dtype == "object" else col
)

products = products.apply(
    lambda col: col.str.strip() if col.dtype == "object" else col
)

print("Whitespace removed successfully!")

Whitespace removed successfully!

In [15]:
# ==========================================================
# STEP 15 : Standardize Text Columns
# Purpose:
# Convert text columns to lowercase for consistency.
# ==========================================================

customers = customers.apply(
    lambda col: col.str.lower() if col.dtype == "object" else col
)

geolocation = geolocation.apply(
    lambda col: col.str.lower() if col.dtype == "object" else col
)

order_items = order_items.apply(
    lambda col: col.str.lower() if col.dtype == "object" else col
)

order_payments = order_payments.apply(
    lambda col: col.str.lower() if col.dtype == "object" else col
)

order_reviews = order_reviews.apply(
    lambda col: col.str.lower() if col.dtype == "object" else col
)

orders = orders.apply(
    lambda col: col.str.lower() if col.dtype == "object" else col
)

products = products.apply(
    lambda col: col.str.lower() if col.dtype == "object" else col
)

print("Text standardized successfully!")

Text standardized successfully!

In [16]:
# ==========================================================
# STEP 16 : Check Unique Values
# Purpose:
# Identify the number of distinct values in each column.
# ==========================================================

print("Customers")
display(customers.nunique())

print("Geolocation")
display(geolocation.nunique())

print("Order Items")
display(order_items.nunique())

print("Order Payments")
display(order_payments.nunique())

print("Order Reviews")
display(order_reviews.nunique())

print("Orders")
display(orders.nunique())

print("Products")
display(products.nunique())

Customers

customer_id                 99441
customer_unique_id          96096
customer_zip_code_prefix    14994
customer_city                4119
customer_state                 27
dtype: int64

Geolocation

geolocation_zip_code_prefix     19015
geolocation_lat                717360
geolocation_lng                717613
geolocation_city                 8011
geolocation_state                  27
dtype: int64

Order Items

order_id               98666
order_item_id             21
product_id             32951
seller_id               3095
shipping_limit_date    93318
price                   5968
freight_value           6999
dtype: int64

Order Payments

order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

Order Reviews

review_id                  99173
order_id                   99441
review_score                   5
review_comment_title        4600
review_comment_message     36921
review_creation_date         637
review_answer_timestamp    99010
dtype: int64

Orders

order_id                         99441
customer_id                      99441
order_status                         8
order_purchase_timestamp         98875
order_approved_at                90733
order_delivered_carrier_date     81018
order_delivered_customer_date    95664
order_estimated_delivery_date      459
dtype: int64

Products

product_id                    32951
product_category_name            73
product_name_lenght              66
product_description_lenght     2960
product_photos_qty               19
product_weight_g               2204
product_length_cm                99
product_height_cm               102
product_width_cm                 95
dtype: int64

In [20]:
# ==========================================================
# STEP 17: Check for Negative Numeric Values
# Purpose:
# Identify unexpected negative values in numeric columns.
# ==========================================================

datasets = {
    "Order Items": order_items,
    "Order Payments": order_payments,
    "Products": products
}

for dataset_name, df in datasets.items():
    
    print(f"\n{dataset_name}")
    
    numeric_columns = df.select_dtypes(include=np.number).columns
    
    for column in numeric_columns:
        
        negative_values = (df[column] < 0).sum()
        
        print(f"{column}: {negative_values}")

Order Items
order_item_id: 0
price: 0
freight_value: 0

Order Payments
payment_sequential: 0
payment_installments: 0
payment_value: 0

Products
product_name_lenght: 0
product_description_lenght: 0
product_photos_qty: 0
product_weight_g: 0
product_length_cm: 0
product_height_cm: 0
product_width_cm: 0

In [19]:
# ==========================================================
# STEP 18 : Verify Missing Values After Cleaning
# ==========================================================

print("Customers")
display(customers.isnull().sum())

print("Geolocation")
display(geolocation.isnull().sum())

print("Order Items")
display(order_items.isnull().sum())

print("Order Payments")
display(order_payments.isnull().sum())

print("Order Reviews")
display(order_reviews.isnull().sum())

print("Orders")
display(orders.isnull().sum())

print("Products")
display(products.isnull().sum())

Customers

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Geolocation

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

Order Items

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Order Payments

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Order Reviews

review_id                      0
order_id                       0
review_score                   0
review_comment_title       88285
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Orders

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Products

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [21]:
# ==========================================================
# STEP 19 : Customers Dataset Cleaning
# Purpose:
# Verify missing values and duplicate customer IDs.
# ==========================================================

print("Missing Values")
display(customers.isnull().sum())

print("\nDuplicate Customer IDs")
print(customers["customer_id"].duplicated().sum())

print("\nDuplicate Customer Unique IDs")
print(customers["customer_unique_id"].duplicated().sum())

Missing Values

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicate Customer IDs
0

Duplicate Customer Unique IDs
3345

In [22]:
# ==========================================================
# STEP 20 : Geolocation Dataset Cleaning
# Purpose:
# Remove duplicate latitude and longitude records.
# ==========================================================

print("Shape Before Removing Duplicates")
print(geolocation.shape)

geolocation = geolocation.drop_duplicates()

print("\nShape After Removing Duplicates")
print(geolocation.shape)

Shape Before Removing Duplicates
(738332, 5)

Shape After Removing Duplicates
(738332, 5)

In [23]:
# ==========================================================
# STEP 21 : Orders Dataset Cleaning
# Purpose:
# Check missing values in order timestamps.
# ==========================================================

print("Missing Values")
display(orders.isnull().sum())

print("\nDuplicate Order IDs")
print(orders["order_id"].duplicated().sum())

Missing Values

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Duplicate Order IDs
0

In [24]:
# ==========================================================
# STEP 22 : Handle Missing Dates
# Purpose:
# Missing delivery dates usually indicate orders that
# were cancelled or not yet delivered.
# These values are retained instead of being removed.
# ==========================================================

date_columns = [
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date"
]

for column in date_columns:

    print(f"{column}")

    print(orders[column].isnull().sum())

order_approved_at
160
order_delivered_carrier_date
1783
order_delivered_customer_date
2965

In [25]:
# ==========================================================
# STEP 23 : Order Items Dataset Cleaning
# Purpose:
# Verify missing values and duplicate order items.
# ==========================================================

print("Missing Values")
display(order_items.isnull().sum())

print("\nDuplicate Records")
print(order_items.duplicated().sum())

Missing Values

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Duplicate Records
0

In [26]:
# ==========================================================
# STEP 24 : Validate Price Columns
# Purpose:
# Check for zero or negative prices and freight values.
# ==========================================================

print("Zero Price Records")
print((order_items["price"] == 0).sum())

print("\nNegative Price Records")
print((order_items["price"] < 0).sum())

print("\nNegative Freight Charges")
print((order_items["freight_value"] < 0).sum())

Zero Price Records
0

Negative Price Records
0

Negative Freight Charges
0

In [27]:
# ==========================================================
# STEP 265: Order Payments Dataset Cleaning
# Purpose:
# Check payment-related information.
# ==========================================================

print("Missing Values")
display(order_payments.isnull().sum())

print("\nNegative Payment Values")
print((order_payments["payment_value"] < 0).sum())

print("\nZero Payment Values")
print((order_payments["payment_value"] == 0).sum())

Missing Values

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Negative Payment Values
0

Zero Payment Values
9

In [28]:
# ==========================================================
# STEP 26 : Order Reviews Dataset Cleaning
# Purpose:
# Verify review scores and missing comments.
# ==========================================================

print("Missing Values")
display(order_reviews.isnull().sum())

print("\nReview Score Distribution")
display(order_reviews["review_score"].value_counts().sort_index())

Missing Values

review_id                      0
order_id                       0
review_score                   0
review_comment_title       88285
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Review Score Distribution

review_score
1    11858
2     3235
3     8287
4    19200
5    57420
Name: count, dtype: int64

In [29]:
# ==========================================================
# STEP 27 : Products Dataset Cleaning
# Purpose:
# Identify missing product information.
# ==========================================================

print("Missing Values")
display(products.isnull().sum())

print("\nDuplicate Product IDs")
print(products["product_id"].duplicated().sum())

Missing Values

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Duplicate Product IDs
0

In [30]:
# ==========================================================
# STEP 28 : Fill Missing Product Category
# Purpose:
# Replace missing categories with 'Unknown'.
# ==========================================================

products["product_category_name"] = products[
    "product_category_name"
].fillna("Unknown")

print("Missing Categories After Filling")
print(products["product_category_name"].isnull().sum())

Missing Categories After Filling
0